# Generated by Django 4.1.7 on 2023-02-18 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='typen',
            table='api_type_notification',
        ),
    ]
