# Generated by Django 4.1.7 on 2023-02-18 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_notification_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='category',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
    ]
