# Generated by Django 4.1.7 on 2023-02-18 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_typen_notification_category_typenuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotification',
            name='channels',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='user',
        ),
        migrations.DeleteModel(
            name='TypeNUser',
        ),
        migrations.DeleteModel(
            name='UserNotification',
        ),
    ]
